<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "slub_find_extend"
 *
 * Auto generated by Extension Builder 2015-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Find configuration for SLUB Catalog',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Christof Rodejohann',
    'author_email' => 'typo3@slub-dresden.de',
    'state' => 'stable',
    'version' => '2.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '13.4.0-13.4.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
